// ----------------------------------------------------------------
// PURPOSE:
// This library implements the Enum for supported adjectives.
//
// REFERENCES:
// - https://authority.pub/positive-personality-adjectives/
// ----------------------------------------------------------------

export const Adjective: object = {
    'accepting': 'readily accepts others without judgment',
    'active': 'engaging in various activities; not passive or sedentary',
    'adaptable': 'able to quickly adjust to change and new circumstances',
    'adventurous': 'willing to risk discomfort and danger to experience new things',
    'affectionate': 'showing affection in words and actions',
    'alert': 'awake and aware of their surroundings and of possible threats',
    'ambitious': 'driven to accomplish great things',
    'amiable': 'friendly; approachable; good-natured',
    'affable': 'friendly; approachable; good-natured',
    'amusing': 'entertaining; fun to watch, read, or listen to',
    'funny': 'entertaining; fun to watch, read, or listen to',
    'assertive': 'not a push-over; able to stand up for themselves',
    'attentive': 'showing thoughtful attention and being present for others',
    'brave': 'ready to face all challenges with courage',
    'brilliant': 'genius-level intelligence and the will to make good use of it',
    'broad-minded': 'open to changes, new ideas, and different viewpoints',
    'calm': 'unperturbed; unruffled; unbothered',
    'candid': 'forthright and frank; truthful',
    'careful': 'showing a disinclination to do harm or showing attention to detail',
    'charming': 'pleasing in appearance and manner',
    'cheerful': 'having a pleasant and positive disposition',
    'clever': 'intelligent and able to quickly make connections',
    'communicative': 'ready to impart information; unreserved; open',
    'confident': 'self-assured or certain of one’s own competence and ability',
    'compassionate': 'kind-hearted and feeling for others',
    'conscientious': 'intent on doing what’s right and performing their duty well',
    'considerate': 'thinking of others and their needs and acting accordingly',
    'courageous': 'doing what’s necessary or beneficial despite fear',
    'courteous': 'treating others with deference and consideration',
    'creative': 'imaginative; artistic; out-of-the-box',
    'curious': 'having an inquiring mind and a desire to see beyond the surface',
    'decisive': 'able to make decisions quickly and firmly',
    'dependable': 'reliable and trustworthy',
    'determined': 'resolute; inexhaustible; unstoppable',
    'diligent': 'hard-working; industrious; dedicated',
    'diplomatic': 'able to resolve disputes between opposing parties',
    'disciplined': 'showing self-control in words and behavior',
    'discreet': 'careful and circumspect in one’s words or actions ',
    'dynamic': 'upbeat and full of energy and new ideas',
    'easygoing': 'laid back; flexible; relaxed',
    'efficient': 'achieving maximum productivity with minimum wasted time and effort',
    'energetic': 'alive with an energy that seems inexhaustible',
    'enthusiastic': 'showing a lot of excitement and enthusiasm',
    'exuberant': 'filled with joyful energy and excitement',
    'fairminded': 'just and impartial',
    'faithful': 'loyal; trustworthy; steadfast',
    'fearless': 'acting without fear',
    'forceful': 'strong; assertive; powerful',
    'forgiving': 'ready to forgive offenses and reconcile',
    'frank': 'honest; candid; unreserved',
    'friendly': 'approachable; amiable; sociable',
    'generous': 'readily giving of one’s one resources to benefit others',
    'genuine': 'precisely what one claims to be; authentic',
    'gentle': 'tenderhearted; sensitive; kind',
    'graceful': 'elegant and showing poise and good taste',
    'gregarious': 'fond of company; sociable; companionable',
    'hard-working': 'diligent; industrious; dedicated',
    'helpful': 'quick to offer help; solicitous; obliging',
    'honest': 'truthful; sincere; frank',
    'hopeful': 'optimistic; sanguine; holding onto hope',
    'humble': 'having a reasonable amount of pride without the need to prove anything',
    'imaginative': 'creative; inventive;',
    'impartial': 'not choosing sides in an argument',
    'independent': 'thinking and acting on their own',
    'intelligent': 'having an above-average mind and the will to use it',
    'intuitive': 'insightful and receptive to their own inner voice',
    'innovative': 'creative; experimental; resourceful',
    'inventive': 'creative; experimental; resourceful',
    'just': 'fair-minded and equitable',
    'kind': 'caring, considerate, and compassionate toward others',
    'liberal': 'open-minded; generous; respectful',
    'loving': 'showing love in words and actions',
    'loyal': 'faithful and supportive',
    'mature': 'dependable, sensible, and wise',
    'merciful': 'compassionate and kind',
    'meticulous': 'careful, detail-oriented, and thorough',
    'modest': 'not inclined to brag or show off; quietly impressive',
    'neat': 'clean, tidy, and organized (or, at least, not cluttered)',
    'optimistic': 'having a positive outlook on life and other people',
    'organized': 'orderly and systematic in their actions and housekeeping',
    'passionate': 'having or expressing strong emotions or beliefs',
    'patient': 'putting others first without complaining',
    'persistent': 'unsinkable or unwilling to give up',
    'pioneering': 'groundbreaking and actively seeking new discoveries',
    'philosophical': 'showing composure in the face of difficulties and disappointments',
    'placid': 'calm and unruffled; preferring harmony and accord',
    'peaceful': 'calm and unruffled; preferring harmony and accord',
    'playful': 'having a childlike, joyful spirit',
    'plucky': 'Resilient and courageous',
    'polite': 'treating others with courtesy and respect',
    'powerful': 'exhibiting a kind of power that exerts influence on their behalf',
    'practical': 'sensible or preferring functionality over aesthetics',
    'proactive': 'thinking ahead and taking an active role',
    'punctual': 'preferring to always be on time',
    'purposeful': 'imbued with a strong sense of purpose and determination',
    'quick-witted': 'quick-thinking or quick to offer a witty reply',
    'quiet': 'solemn or preferring to observe quietly',
    'rational': 'sensible, fair, and logical',
    'reasonable': 'sensible, fair, and logical',
    'reliable': 'as good as their word',
    'reserved': 'private; careful; restrained',
    'resolute': 'purposeful; determined; unwavering',
    'resourceful': 'finding quick and clever ways to overcome challenges',
    'romantic': 'having an idealized view of reality',
    'self-motivated': 'able to motivate themselves internally',
    'sensible': 'level-headed; reasonable; realistic',
    'sensitive': 'easily responds to things',
    'sincere': 'nhonest and genuine',
    'skillful': 'being an expert or proficient at something',
    'smart': 'either intelligent or stylish ',
    'sociable': 'being at ease around people — and putting them at ease',
    'straightforward': 'telling the unvarnished truth in plain language',
    'strong': 'physically, mentally, or emotionally powerful and resilient',
    'supportive': 'accepting and ready to help or to be there when needed',
    'sympathetic': 'shows they understand and care about other people’s problems',
    'tenacious': 'determined to succeed and refusing to let go of the goal',
    'tactful': 'knowing what not to say in difficult situations',
    'thoughtful': 'considerate; anticipating someone’s needs or desires',
    'tidy': 'neat and well-kept',
    'tolerant': 'able to hear dissenting viewpoints or beliefs with',
    'tough': 'resilient; strong; durable',
    'trustworthy': 'worthy of someone’s complete trust',
    'unassuming': 'genuine and unaffected',
    'understanding': 'seeing beyond the surface to grasp the essential',
    'versatile': 'able to excel at a variety of tasks or challenges',
    'warmhearted': 'compassionate, kind, and quick to offer help',
    'wise': 'experienced and insightful',
    'witty': 'clever and funny',
}
