// ----------------------------------------------------------------
// PURPOSE:
// This library implements the Enum for supported adverbs.
//
// REFERENCES:
// - https://sites.google.com/site/maycaingles2011/lessons-1/adverbs
// - https://sites.google.com/site/maycaingles2011/lessons-1/adverbs/place-adverbs
// ----------------------------------------------------------------

export const Connector: object = {
    'firstly': '',
    'secondly': '',
    'thirdly': '',
    'absolutely': '',
    'angrily': '',
    'awfully': '',
    'badly': '',
    'bravely': '',
    'beautifully': '',
    'brilliantly': '',
    'carefully': '',
    'completely': '',
    'confortably': '',
    'costly': '',
    'deeply': '',
    'early': '',
    'easily': '',
    'effortlessly': '',
    'exactly': '',
    'excitedly': '',
    'extremely': '',
    'fortunately': '',
    'finally': '',
    'fluently': '',
    'frequently': '',
    'fully': '',
    'gradually': '',
    'happily': '',
    'hardly': '',
    'heartily': '',
    'honestly': '',
    'immediately': '',
    'instantly': '',
    'lastly': '',
    'loudly': '',
    'luckily': '',
    'mainly': '',
    'nearly': '',
    'nicely': '',
    'noisily': '',
    'patiently': '',
    'peacefully': '',
    'perfectly': '',
    'politely': '',
    'possibly': '',
    'proudly': '',
    'quickly': '',
    'quietly': '',
    'rapidly': '',
    'rarely': '',
    'really': '',
    'recently': '',
    'scarcely': '',
    'seriously': '',
    'shyly': '',
    'slightly': '',
    'slowly': '',
    'strangely': '',
    'strongly': '',
    'successfully': '',
    'suddenly': '',
    'sweetly': '',
    'terribly': '',
    'tightly': '',
    'tragically': '',
    'unfortunately': '',
    'usually': '',
    'vigorously': '',
    'violently': '',
    'weakly': '',
    'weekly': '',
    'wonderfully': '',
    'everywhere': '',
    'somewhere': '',
    'anywhere': '',
    'nowhere': '',
    'where': '',
    'what': '',
    'how': '',
    'why': '',
    'that': '',
    'when': '',
    'in which': '',
    'which': '',
    'whom': '',
    'whose': '',
    'here': '',
    'there': '',
    'above': '',
    'down': '',
    'up': '',
    'inside': '',
    'near': '',
    'far': '',
    'behind': '',
    'forward': '',
    'under': '',
    'in front': '',
    'in front of': '',
    'opposite': '',
    'over': '',
    'around': '',
    'on top of': '',
    'through': '',
    'back': '',
    'abroad': '',
    'outside': '',
    'underground': '',
    'upstairs': '',
    'monday': '',
    'tuesday': '',
    'wednesday': '',
    'thursday': '',
    'friday': '',
    'saturday': '',
    'sunday': '',
    'immediately': '',
    'recently': '',
    'soon': '',
    'later': '',
    'then': '',
    'now': '',
    'yesterday': '',
    'today': '',
    'tomorrow': '',
    'finally': '',
    'afterwards': '',
    'eventually': '',
    'already': '',
    'still': '',
    'yet': '',
    'just': '',
    'ever': '',
    'never': '',
    'anymore': '',
    'no longer': '',
    'next week': '',
    'next month': '',
    'next year': '',
    'last week': '',
    'last month': '',
    'last year': '',
}
