// ----------------------------------------------------------------
// PURPOSE:
// This library implements the Enum for supported connectors.
//
// REFERENCES:
// - https://sites.google.com/site/maycaingles2011/writing/linkers-and-connectors
// - https://thefluentlife.com/content/linkers-connectors-english-grammar-guide-types-cause-effect-purpose/
// ----------------------------------------------------------------

export const Connector: object = {
    'and': 'He and other members went to the party.',
    'in spite of': 'Link two contrasting ideas. Followed by a noun phrase',
    'although': 'Link two contrasting ideas. Followed by a sentence.',
    'though': 'Link two contrasting ideas. Followed by a sentence.',
    'even though': 'Link two contrasting ideas. Followed by a sentence.',
    'however': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'nevertheless': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'still': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'yet': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'even so': 'He had a headache but even so, he went to pick her up.',
    'on the contrary': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'in contrast': 'Introduce a new idea which marks a contrast with previously stated ideas. Introduced by a comma.',
    'on the one hand': 'Links two contrasting ideas / paragraphs.',
    'on the other hand': 'Links two contrasting ideas / paragraphs.',
    'contrary to': 'Link two contrasting ideas. Followed by a noun phrase.',
    'whereas': 'link two contrasting ideas. Not separated by commas.',
    'while': 'link two contrasting ideas. Not separated by commas.',
    'because': 'Subordinate sentences introduced by because always appear in final position.',
    'as': 'Subordinate sentences introduced by because always appear in final position.',
    'since': 'Since she loves ice cream so much, I decided to give her an ice-cream printed dress.',
    'seeing that': 'Seeing that he was losing the fight, he started blaming her mother.',
    'because of': 'Introduce a noun phrase.',
    'on account of': 'Both the siblings were mentally unstable on account of their disturbed childhood.',
    'owing to': 'Introduce a noun phrase.',
    'due to': 'The match got cancelled due to the heavy rain.',
    'in order to': 'In order to prove him wrong, he started shouting.',
    'in order that': 'I want to finish my work today so that I can spend my weekend relaxing.',
    'so as to': 'You have to study hard so as to improve your career.',
    'so that': 'Give me your resume so that I can forward it to the right department.',
    'consequently': 'I got stuck in the traffic consequently I missed the flight.',
    'as a consequence': 'Followed by a noun phrase.',
    'as a result': 'As a result of the heavy rain, the match got cancelled.',
    'therefore': 'I slept very late last night, therefore, I missed the morning prayer.',
    'so': 'The blue bag was full so he kept the packet in the yellow bag.',
    'as a consequence of': 'Followed by a noun phrase.',
    'as a result of': 'Followed by a noun phrase.',
    'moreover': 'You have to cook lunch and moreover that you also have to go to the market in the evening.',
    'furthermore': 'He was tired and hungry furthermore he was ill.',
    'further': 'I introduced him to the other members and that’s it, I had no further conversation.',
    'in addition': 'The umbrella will protect you from the Sun, besides it will also come handy if rainfall starts.',
    'in addition to': 'In addition to the notes, the teacher also suggested some reference books for the preparation.',
    'besides': 'Used after a strong pause and separated from the sentences. Introduced by a comma.',
    "what's more": 'What’s more, now you have all that is required to have a wonderful vacation.',
    'as well as': 'The sound, as well as the picture quality, is amazing.',
    'for example': 'For example, take the rising graph of air pollution.',
    'for instance': 'I like a few vegetables, for instance, potato, cabbage etc.",
    'such as': 'There are many famous railway stations in the state of West Bengal such as Howrah, Sealdah, Ghum etc.',
    'in this case': 'In this case, emotion will matter more than logic.',
    'but': 'followed by a noun phrase or a sentence.',
    'in spite of': 'It is placed at the beginning or in the middle of the sentence.',
    'despite': 'It is placed at the beginning or in the middle of the sentence.',
    'in spite of the fact that': 'followed by a complete sentence.',
    'apart from': 'Apart from English, she speaks French.',
    'except for': 'Except for English, she speaks French.',
    'first': 'First, you should go to the washroom and take a bath.',
    'firstly': '',
    'first of all': 'First of all, they are not my family and I can not be held responsible for their immature behaviour.',
    'to being with': '',
    'to start with': 'To start with, I asked her to tell us about her hobbies.',
    'second': '',
    'secondly': 'Secondly, you have to manage the team.',
    'then': 'Once you reach the office, then make a call to the supervisor.',
    'third': '',
    'thirdly': '',
    'or': '',
    'alternativelly': 'You can go to that Italian restaurant or alternatively you can even choose the Mexican food counter on the opposite side of the road.',
    'by the way': 'By the way, here is my card.',
    'unless': 'I won’t pay you unless you drop me to the right stoppage.',
    'after that': '',
    'and finally': 'And finally, the day of the verdict came.',
    'finally': 'Finally, the war came to an end.',
    'in short': 'The outing, in short, could not lift up my mood.',
    'to sum up': '',
    'in conlusion': 'In conclusion, it is always better to take prevention than cure.',
    'lastly': 'Lastly, we had our dinner and left.',
    'last but not least': '',
    'at first sight': 'At first sight, he appeared to be very arrogant.',
    'and then': 'John came from swimming and then left for basketball coaching.',
    'in the first place': 'In the first place, take care of the pets and then do the rest of your work.',
    'in the second place': '',
    'on top of that': 'And on top of that, you will also get incentives.',
    'all the same': '',
    'actually': '',
    'also': 'He was told to study and also to take care of the dog.',
    'indeed': 'She was sweet indeed but needed proper grooming.',
    'of course': 'Sportsmen have a competitive approach while playing but of course, that should not be carried off the ground',
    'as a matter of fact': '',
    'really': '',
    'in fact': '',
    'as far as I am concerned': 'As far as I am concerned, I am done with it',
    'from my point of view': 'The sin is terrific from my point of view.',
    'i agree with': 'I agree with her decision.',
    'i disagree with': 'I disagree with the thought of buying a new car even when we already have two.',
    'personally': 'The show must go on, personally I think so.',
    'in my opinion': '',
    'it is true that': 'It is true that a lot of hard work has been put in here but I really can’t see any reflection of that.',
    'i think that': 'He has run away, I think.',
    'i personally think that': '',
    'to be honest': 'To be honest, I don’t support the idea of destroying her career.',
    'to be frank': '',
    'to tell the truth': 'To tell the truth, I didn’t like the show at all.',
    'in other words': 'The problem, In other words, is that we have to re-write the whole script.',
    'above all': 'The idea behind the meeting is, above all, to make the employees aware of the current financial crisis faced by the company.',
    'at least': 'At least now when you know that we are here, you can jump in any day.',
    'basically': 'The cake is basically full of chocolates.',
    'especially': 'It’s tough to sleep, especially after the strong coffee we drank.',
    'essentially': 'An electric kettle is useful essentially for the winter months.',
    'in general': 'Old people, in general, like to spend time with their grandkids.',
    'in particular': 'All women, in particular, have to be strong and determined.',
    'more or less': 'There will be more or less 30 guests.',
    'on the whole': '',
    'to a certain extent': '',
    'certainly': 'Certainly, she has witnessed something cruel otherwise she would not be so nervous.',
    'specifically': 'He specifically looked for a diamond-studded ring.',
    'significantly': 'Her health was significantly improving.',
    'notably': 'Her academic career has been notably amazing.',
    'to some degree': '',
    'all in all': '',
    'in brief': '',
    'in conclusion': '',
    'regarding': '',
    'all of a sudden': '',
    'in the end': '',
    'in the meantime': '',
    'meanwhile': '',
    'next': 'The next episode is going to be very interesting.',
    'suddenly': '',
    'always': '',
    'often': '',
    'seldom': '',
    'scarcely': '',
    'hardly': '',
    'ever': '',
    'never': '',
    'sometimes': '',
    'now': '',
    'before': 'You have to try before coming to a conclusion.',
    'after': 'He also left after his wife.',
    'today': '',
    'thus': '',
    'tomorrow': ''
    'conversely': 'Zoey may not perform up to the mark in science subjects, but conversely, he has an impeccable hold in literature.'
    'at the same time': 'She felt guilty and depressed at the same time.',
    'tonight': '',
    'nowadays': '',
    'soon': 'They are soon to graduate.',
    'later': 'Later, it all got resolved.',
    'hence': 'He is looking for a formal trouser because he has an important meeting tomorrow.',
    'too': 'He too misbehaved with the maid.'
    'not only': 'We are not only harming the environment but also becoming inhuman day by day.',
    'equally': 'Both of them are equally talented.',
    'as if': 'It seems as if they have cried a lot.',
    'similarly': 'We have chosen our group members, similarly, you can do that too.',
    'comparable': 'Today’s weather is comparable with that of Darjeeling.',
    'like': 'He was determined to get a high-rank job like his cousin.',
    'in like manner': 'All responded in a like manner.',
    'in the same way': 'Now do the rest of the drawing in the same way as I did.',
    'illustrated by': 'The entire story was illustrated by Mr Sameer in a very clear manner.',
}
