// ----------------------------------------------------------------
// PURPOSE:
// This library implements the Enum for supported idoms.
//
// REFERENCES:
// - https://sites.google.com/site/maycaingles2011/idioms-expressions-and-proverbs/idioms
// ----------------------------------------------------------------

export const Idiom: object = {
    "a bird in the hand is worth two in the bush": "having something that is certain is much better than taking a risk for more, because chances are you might lose everything.",
    "a blessing in disguise": "something good that isn't recognized at first.",
    "a chip on your shoulder": "being upset for something that happened in the past.",
    "a dime a dozen": "anything that is common and easy to get.",
    "a doubting thomas": "a skeptic who needs physical or personal evidence in order to believe something.",
    "a drop in the bucket": "a very small part of something big or whole.",
    "a fool and his money are easily parted": "it's easy for a foolish person to lose his/her money.",
    "a house divided against itself cannot stand": "everyone involved must unify and function together or it will not work out.",
    "a leopard can't change his spots": "you cannot change who you are.",
    "a penny saved is a penny earned": "by not spending money, you are saving money (little by little).",
    "a picture paints a thousand words": "a visual presentation is far more descriptive than words.",
    "a piece of cake": "a task that can be accomplished very easily.",
    "a slap on the wrist": "a very mild punishment.",
    "a taste of your own medicine": "when you are mistreated the same way you mistreat others.",
    "a toss-up": "a result that is still unclear and can go either way.",
    "actions speak louder than words": "it's better to actually do something than just talk about it.",
    "add fuel to the fire": "whenever something is done to make a bad situation even worse than it is.",
    "against the clock": "rushed and short on time.",
    "all bark and no bite": "when someone is threatening and/or aggressive but not willing to engage in a fight.",
    "all greek to me": "meaningless and incomprehensible like someone who cannot read, speak, or understand any of the greek language would be.",
    "all in the same boat": "when everyone is facing the same challenges.",
    "an arm and a leg": "very expensive. a large amount of money.",
    "an axe to grind": "to have a dispute with someone.",
    "apple of my eye": "someone who is cherished above all others.",
    "as high as a kite": "anything that is high up in the sky.",
    "at the drop of a hat": "willing to do something immediately.",
    "back seat driver": "people who criticize from the sidelines, much like someone giving unwanted advice from the back seat of a vehicle to the driver.",
    "back to square one": "having to start all over again.",
    "back to the drawing board": "when an attempt fails and it's time to start all over.",
    "baker's dozen": "thirteen.",
    "barking up the wrong tree": "a mistake made in something you are trying to achieve.",
    "beat a dead horse": "to force an issue that has already ended.",
    "beating around the bush": "avoiding the main topic. not speaking directly about the issue.",
    "bend over backwards": "do whatever it takes to help. willing to do anything.",
    "between a rock and a hard place": "stuck between two very bad options.",
    "bite off more than you can chew": "to take on a task that is way to big.",
    "bite your tongue": "to avoid talking.",
    "blood is thicker than water": "the family bond is closer than anything else.",
    "blue moon": "a rare event or occurance.",
    "break a leg": "a superstitious way to say 'good luck' without saying 'good luck', but rather the opposite.",
    "buy a lemon": "to purchase a vehicle that constantly gives problems or stops running after you drive it away.",
    "can't cut the mustard ": "someone who isn't adequate enough to compete or participate.",
    "cast iron stomach": "someone who has no problems, complications or ill effects with eating anything or drinking anything.",
    "charley horse": "stiffness in the leg / a leg cramp.",
    "chew someone out": "verbally scold someone.",
    "chip on his shoulder": "angry today about something that occured in the past.",
    "chow down": "to eat.",
    "close but no cigar": "to be very near and almost accomplish a goal, but fall short.",
    "cock and bull story": "an unbelievable tale.",
    "come hell or high water": "any difficult situation or obstacle.",
    "crack someone up": "to make someone laugh.",
    "cross your fingers": "to hope that something happens the way you want it to.",
    "cry over spilt milk": "when you complain about a loss from the past.",
    "cry wolf": "intentionally raise a false alarm.",
    "cup of joe": "a cup of coffee.",
    "curiosity killed the cat": "being inquisitive can lead you into a dangerous situation.",
    "cut to the chase": "leave out all the unnecessary details and just get to the point.",
    "dark horse": "one who was previously unknown and is now prominent.",
    "dead ringer": "100% identical. a duplicate.",
    "devil's advocate": "someone who takes a position for the sake of argument without believing in that particular side of the arguement.",
    "dog days of summer": "the hottest days of the summer season.",
    "don't count your chickens before they hatch": "don't rely on it until your sure of it.",
    "don't look a gift horse in the mouth": "when someone gives you a gift, don't be ungrateful.",
    "don't put all your eggs in one basket": "do not put all your resources in one possibility.",
    "doozy": "something outstanding.",
    "down to the wire": "something that ends at the last minute or last few seconds.",
    "drastic times call for drastic measures": "when you are extremely desperate you need to take extremely desperate actions.",
    "drink like a fish": "to drink very heavily.",
    "drive someone up the wall": "to irritate and/or annoy very much.",
    "dropping like flies": "a large number of people either falling ill or dying.",
    "dry run": "rehearsal.",
    "eighty six": "a certain item is no longer available. or this idiom can also mean, to throw away.",
    "elvis has left the building": "the show has come to an end. it's all over.",
    "ethnic cleansing": "killing of a certain ethnic or religious group on a massive scale.",
    "every cloud has a silver lining": "be optomistic, even difficult times will lead to better days.",
    "everything but the kitchen sink": "almost everything and anything has been included.",
    "excuse my french": "please forgive me for cussing.",
    "cock and bull story": "an unbelievable tale.",
    "cock and bull story": "an unbelievable tale.",
    "feeding frenzy": "an aggressive attack on someone by a group.",
    "field day": "an enjoyable day or circumstance.",
    "finding your feet": "to become more comfortable in whatever you are doing.",
    "finger lickin' good": "a very tasty food or meal.",
    "fixed in your ways": "not willing or wanting to change from your normal way of doing something.",
    "flash in the pan": "something that shows potential or looks promising in the beginning but fails to deliver anything in the end.",
    "flea market": "a swap meet. a place where people gather to buy and sell inexpensive goods.",
    "flesh and blood": "this idiom can mean living material of which people are made of, or it can refer to someone's family.",
    "flip the bird": "to raise your middle finger at someone.",
    "foam at the mouth": "to be enraged and show it.",
    "fools' gold": "iron pyrites, a worthless rock that resembles real gold.",
    "french kiss": "an open mouth kiss where tongues touch.",
    "from rags to riches": "to go from being very poor to being very wealthy.",
    "fuddy-duddy": "an old-fashioned and foolish type of person.",
    "full monty": "this idiom can mean either, the whole thing or completely nude.",
    "funny farm": "a mental institutional facility.",
    "get down to brass tacks": "to become serious about something.",
    "get over it": "to move beyond something that is bothering you.",
    "get up on the wrong side of the bed": "someone who is having a horrible day.",
    "get your walking papers": "get fired from a job.",
    "give him the slip": "to get away from. to escape.",
    "go down like a lead balloon": "to be received badly by an audience.",
    "go for broke": "to gamble everything you have.",
    "go out on a limb": "put yourself in a tough position in order to support someone/something.",
    "go the extra mile": "going above and beyond whatever is required for the task at hand.",
    "good samaritan": "someone who helps others when they are in need, with no discussion for compensation, and no thought of a reward.",
    "graveyard shift": "working hours from about 12:00 am to 8:00 am. the time of the day when most other people are sleeping.",
    "great minds think alike": "intelligent people think like each other.",
    "green room": "the waiting room, especially for those who are about to go on a tv or radio show.",
    "gut feeling": "a personal intuition you get, especially when feel something may not be right.",
    "haste makes waste": "quickly doing things results in a poor ending.",
    "hat trick": "when one player scores three goals in the same hockey game. this idiom can also mean three scores in any other sport, such as 3 homeruns, 3 touchdowns, 3 soccer goals, etc.",
    "have an axe to grind": "to have a dispute with someone.",
    "he lost his head": "angry and overcome by emotions.",
    "head over heels": "very excited and/or joyful, especially when in love.",
    "hell in a handbasket": "deteriorating and headed for complete disaster.",
    "high five": "slapping palms above each others heads as celebration gesture.",
    "high on the hog": "living in luxury.",
    "hit the books": "to study, especially for a test or exam.",
    "hit the hay": "go to bed or go to sleep.",
    "hit the nail on the head": "do something exactly right or say something exactly right.",
    "hit the sack": "go to bed or go to sleep.",
    "hocus pocus": "in general, a term used in magic or trickery.",
    "hold your horses": "be patient.",
    "icing on the cake": "when you already have it good and get something on top of what you already have.",
    "idle hands are the devil's tools": "you are more likely to get in trouble if you have nothing to do.",
    "if it's not one thing, it's another": "when one thing goes wrong, then another, and another...",
    "in like flynn": "to be easily successful, especially when sexual or romantic.",
    "in the bag": "to have something secured.",
    "in the buff": "nude.",
    "in the heat of the moment": "overwhelmed by what is happening in the moment.",
    "in your face": "an aggressive and bold confrontation.",
    "it takes two to tango": "a two person conflict where both people are at fault.",
    "it's a small world": "you frequently see the same people in different places.",
    "its anyone's call": "a competition where the outcome is difficult to judge or predict.",
    "ivy league": "since 1954 the ivy league has been the following universities: columbia, brown, cornell, dartmouth, yale, pennsylvania, princeton, and harvard.",
    "jaywalk": "crossing the street (from the middle) without using the crosswalk.",
    "joshing me": "tricking me.",
    "keep an eye on him": "you should carefully watch him.",
    "keep body and soul together": "to earn a sufficient amount of money in order to keep yourself alive .",
    "keep your chin up": "to remain joyful in a tough situation.",
    "kick the bucket": "die.",
    "kitty-corner": "diagonally across. sometimes called catty-corner as well.",
    "knee jerk reaction": "a quick and automatic response.",
    "knock on wood": "knuckle tapping on wood in order to avoid some bad luck.",
    "know the ropes": "to understand the details.",
    "last but not least": "an introduction phrase to let the audience know that the last person mentioned is no less important than those introduced before him/her.",
    "lend me your ear": "to politely ask for someone's full attention.",
    "let bygones be bygones": "to forget about a disagreement or arguement.",
    "let sleeping dogs lie": "to avoid restarting a conflict.",
    "let the cat out of the bag": "to share a secret that wasn't suppose to be shared.",
    "level playing field": "a fair competition where no side has an advantage.",
    "like a chicken with its head cut off": "to act in a frenzied manner.",
    "liquor someone up": "to get someone drunk.",
    "long in the tooth": "old people (or horses).",
    "loose cannon": "someone who is unpredictable and can cause damage if not kept in check.",
    "make no bones about": "to state a fact so there are no doubts or objections.",
    "method to my madness": "strange or crazy actions that appear meaningless but in the end are done for a good reason.",
    "mumbo jumbo": "nonsense or meaningless speech.",
    "mum's the word": "to keep quiet. to say nothing.",
    "nest egg": "savings set aside for future use.",
    "never bite the hand that feeds you": "don't hurt anyone that helps you.",
    "new kid on the block": "someone new to the group or area.",
    "new york minute": "a minute that seems to go by quickly, especially in a fast paced environment.",
    "no dice": "to not agree. to not accept a proposition.",
    "no room to swing a cat": "an unsually small or confined space.",
    "not playing with a full deck": "someone who lacks intelligence.",
    "off on the wrong foot": "getting a bad start on a relationship or task.",
    "off the hook": "no longer have to deal with a tough situation.",
    "off the record": "something said in confidence that the one speaking doesn't want attributed to him/her.",
    "on pins and needles": "anxious or nervous, especially in anticipation of something.",
    "on the fence": "undecided.",
    "on the same page": "when multiple people all agree on the same thing.",
    "out of the blue": "something that suddenly and unexpectedly occurs.",
    "out on a limb": "when someone puts themself in a risky situation.",
    "out on the town": "to enjoy yourself by going out.",
    "over my dead body": "when you absolutely will not allow something to happen.",
    "over the top": "very excessive.",
    "pass the buck": "avoid responsibility by giving it to someone else.",
    "pedal to the metal": "to go full speed, especially while driving a vehicle.",
    "peeping tom": "someone who observes people in the nude or sexually active people, mainly for his own gratification.",
    "pick up your ears": "to listen very carefully.",
    "pig in a poke": "a deal that is made without first examining it.",
    "pig out ": "to eat alot and eat it quickly.",
    "pipe down": "to shut-up or be quiet.",
    "practice makes perfect": "by constantly practicing, you will become better.",
    "pull the plug": "to stop something. to bring something to an end.",
    "pulling your leg": "tricking someone as a joke.",
    "put a sock in it": "to tell noisy person or a group to be quiet.",
    "queer the pitch": "destroy or ruin a plan.",
    "raincheck": "an offer or deal that is declined right now but willing to accept later.",
    "raining cats and dogs": "a very loud and noisy rain storm.",
    "ring fencing": "seperated usual judgement to guarantee protection, especially project funds.",
    "rise and shine": "time to get out of bed and get ready for work/school.",
    "rome was not built in one day": "if you want something to be completely properly, then its going to take time.",
    "rule of thumb": "a rough estimate.",
    "run out of steam": "to be completely out of energy.",
    "saved by the bell": "saved at the last possible moment.",
    "scapegoat": "someone else who takes the blame.",
    "scot-free": "to escape and not have to pay.",
    "sick as a dog": "to be very sick (with the flu or a cold).",
    "sitting shotgun": "riding in the front passenger seat of a car.",
    "sixth sense": "a paranormal sense that allows you to communicate with the dead.",
    "skid row": "the rundown area of a city where the homeless and drug users live.",
    "smell a rat": "to detect somone in the group is betraying the others.",
    "smell something fishy": "detecting that something isn't right and there might be a reason for it.",
    "son of a gun": "a scamp.",
    "southpaw": "someone who is left-handed.",
    "spitting image": "the exact likeness or kind.",
    "start from scratch": "to do it all over again from the beginning.",
    "the ball is in your court": "it is your decision this time.",
    "the best of both worlds": "there are two choices and you have them both.",
    "the bigger they are the harder they fall": "while the bigger and stronger opponent might be alot more difficult to beat, when you do they suffer a much bigger loss.",
    "the last straw": "when one small burden after another creates an unbearable situation, the last straw is the last small burden that one can take.",
    "the whole nine yards": "everything. all of it.",
    "third times a charm": "after no success the first two times, the third try is a lucky one.",
    "tie the knot": "to get married.",
    "til the cows come home": "a long time.",
    "to make a long story short": "something someone would say during a long and boring story in order to keep his/her audience from losing attention. usually the story isn't shortened.",
    "to steal someone's thunder": "to take the credit for something someone else did.",
    "tongue and cheek": "humor, not to be taken serious.",
    "turn a blind eye": "refuse to acknowledge something you know is real or legit.",
    "twenty three skidoo": "to be turned away.",
    "under the weather": "feeling ill or sick.",
    "up a blind alley": "going down a course of action that leads to a bad outcome.",
    "use your loaf": "use your head. think smart.",
    "van gogh's ear for music": "tone deaf.",
    "variety is the spice of life": "the more experiences you try the more exciting life can be.",
    "wag the dog": "a diversion away from something of greater importance.",
    "water under the bridge": "anything from the past that isn't significant or important anymore.",
    "wear your heart on your sleeve": "to openly and freely express your emotions.",
    "when it rains, it pours": "since it rarely rains, when it does it will be a huge storm.",
    "when pigs fly ": "something that will never ever happen.",
    "wild and woolly": "uncultured and without laws.",
    "wine and dine": "when somebody is treated to an expensive meal.",
    "without a doubt": "for certain.",
    "x marks the spot": "a phrase that is said when someone finds something he/she has been looking for.",
    "you are what you eat": "in order to stay healthy you must eat healthy foods.",
    "you can't judge a book by its cover": "decisions shouldn't be made primarily on appearance.",
    "you can't take it with you": "enjoy what you have and not what you don't have, since when you die you cannot take things (such as money) with you.",
    "your guess is as good as mine": "i have no idea.",
    "zero tolerance": "no crime or law breaking big or small will be overlooked.",
    "a dog's life": "una vida de perros",
    "as sick as a dog": "muy enfermo",
    "to be a dog in the manger": "ser (como) el perro del hortelano (que ni come ni deja comer)",
    "to be dressed up like a dog's dinner": "estar/ir todo,-a emperifollado,-a",
    "to be the dog's bollocks": "ser algo cojonudo",
    "every dog has its/his day": "a todo el mundo, incluso al más insignificante,  le llega su momento de gloria",
    "give a dog a bad name": "calumnia que algo queda, si alguien es calumniado, le es luego muy difícil recuperar su buen nombre",
    "to go to the dogs": "venirse abajo, irse al traste",
    "dog eat dog": "competencia feroz ",
    "to help a lame dog over a stile": "ayudar a alguien que está en apuros",
    "let sleeping dogs lie": "no despiertes al león dormido, mejor no meneallo",
    "like a dog with two tails": "como niño con zapatos nuevos",
    "to make a dog's breakfast/dinner of": "hacer algo muy mal, hacer un desastre/desaguisado",
    "not have/stand a dog's chance": "no tener ni la más mínima oportunidad",
    "to put on the dog": "darse pisto/tono",
    "to rain cats and dogs": "llover a cántaros, caer chuzos de punta",
    "a shaggy dog story": "un chiste viejo, largo y malo.",
    "the tail wagging the dog": "el mundo al revés (la parte menos importante controla a la parte más importante)",
    "there's life in the old dog yet": "no está acabado todavía",
    "to treat sb like a dog": "tratar a alguien como a un perro",
    "you can't teach an old dog new tricks": "(refrán) es difícil hacer cambiar de ideas, hábitos, etc. a las personas mayores",
    "to hit below the belt": "dar un golpe bajo",
    "to tighten one's belt": "apretarse el cinturón",
    "to be a wet blanket": "ser un aguafiestas",
    "the boot/shoe is on the other foot": "se han cambiado las tornas/las cosas han cambiado",
    "cap in hand": "humildemente, respetuosamente",
    "a feather in one's cap": "apuntarse un tanto",
    "if the cap fits, wear it": "quien se pica, ajos come",
    "to fit like a glove": "sentar a alguien como un guante",
    "to handle someone with kid gloves": "tratar a alguien con guantes de seda",
    "at the drop of a hat": "enseguida, a las primeras de cambio",
    "to talk through one's hat": "decir tonterías sobre algo que no se conoce, haber oído campanas y no saber dónde",
    "to keep something under one's hat": "no decir ni pío de algo a alguien, mantener en secreto",
    "to wash one's dirty linen in public": "lavar los trapos sucios en público",
    "to be in someone's shoes": "estar en el pellejo de alguien.",
    "to put oneself in someone else's shoes": "ponerse en el lugar de alguien",
    "on a shoestring": "con escasos medios/presupuesto",
    "to have an ace up one's sleeve": "guardar un as en la manga",
    "to wear one's heart on one's sleeve -no ocultar los sentimientos, ser transparente",
    "to pull one's socks up": "esforzarse, esmerarse",
    "to be a stuffed shirt": "ser una persona estirada/engreída",
    "to wear the the pants": "llevar los pantalones",
    "to throw in the towel": "tirar la toalla",
    "that's the point": "eso es, de eso se trata",
    "that's not the point": "no se trata de eso",
    "a sore point": "un asunto delicado/espinoso, una cuestión que levanta ampollas",
    "to be a case in point": "ser un ejemplo apropiado, que viene al pelo/a cuento",
    "to be beside the point": "ser irrelevante",
    "to be on the point of doing sth": "estar a punto de hacer algo",
    "to be to the point": "venir al caso",
    "to get off the point": "salirse del tema, irse por las ramas",
    "to get the point": "entender lo que alguien quiere decir",
    "to get to the point": "ir al grano",
    "in point of fact": "de hecho",
    "to keep to the point": "no salirse del tema, no irse por las ramas",
    "to make a point of doing sth": "asegurarse de hacer algo",
    "to make one’s point": "dejar clara una idea",
    "to miss the point": "no entender algo",
    "not to put too fine a point on it": "hablando en plata",
    "the point at issue": "el tema/asunto en cuestión",
    "point of view": "punto de vista",
    "to press a point home": "conseguir convencer a alguien de algo",
    "to see the point": "entender el por qué de algo",
    "to stretch a point": "hacer una excepción",
    "sb’s weak point(s)": "el punto débil/flaco de alguien",
    "what’s the point of": "¿de qué sirve...?",
    "you have a point there": "en eso llevas razón",
}
