// ----------------------------------------------------------------
// PURPOSE:
// This library implements the Enum for supported proverbs.
//
// REFERENCES:
// - https://sites.google.com/site/maycaingles2011/idioms-expressions-and-proverbs/english-proverbs
// ----------------------------------------------------------------

export const Proverb: object = {
    'a bird in the hand is worth two in the bush': '',
    'a cat in gloves catches no mice': '',
    'a stitch in time saves nine': '',
    'a word is enough to the wise': '',
    'absence makes the heart grow fonder': '',
    'actions speak louder than words': '',
    'all cats are grey in the dark': '',
    'all roads lead to Rome': '',
    'all that glitters is not gold': '',
    'all work and no play makes Jack a dull boy': '',
    'an apple a day keeps the doctor away': '',
    'appearances are deceptive': '',
    'barking dogs never bite': '',
    'better late than never': '',
    'better safe than sorry': '',
    "better the devil you know than the devil you don't know": '',
    'birds of a feather flock together': '',
    'blood is thicker than water': '',
    'chip off the old block': '',
    'common sense is the least common of senses': '',
    'do what is right, come what may': '',
    "don't cry before you are hurt": '',
    "don't look a gift-horse in the mouth": '',
    "don't meet trouble halfway": '',
    "don't put all your eggs in one basket": '',
    'early to bed, early to rise, makes the man healthy, wealthy and wise': '',
    'every cloud has a silver lining': '',
    'every law has its loophole': '',
    'every time the sheep bleats, it loses a mouthful': '',
    'experience is the mother of knowledge': '',
    'finders, keepers; losers, weepers': '',
    'give a dog a bad name and hang it': '',
    'god tempers the wind to the shorn lamb': '',
    'half a loaf is better than none': '',
    'he that fights and runs away, lives to fight another day': '',
    'hunt with cats and you catch only rats': '',
    'in for a penny, in for a pound': '',
    'it never rains, but it pours': '',
    "it's good fishing in troubled waters": '',
    "it's never too late to learn": '',
    "it's no good crying over spilt milk": '',
    "it's the last straw that breaks the camel's back": '',
    'let bygones be bygones': '',
    'many hands make light work': '',
    'money is the root of all evil': '',
    'more haste, less speed': '',
    'never trouble trouble till trouble troubles you': '',
    'nothing ventured, nothing gained': '',
    "one man's meat is another man's poison": '',
    "people who live in glass houses shouldn't throw stones": '',
    'politeness costs nothing': '',
    "rome wasn't built in a day": '',
    'take care of the pennies, and the pounds will take care of themselves': '',
    "the apple doesn't fall far from the tree": '',
    'the die is cast': '',
    'the early bird catches the worm': '',
    'the grass is always greener on the other side of the fence': '',
    "the shoemaker's son goes always barefoot": '',
    "there's many a slip twixt cup and lip": '',
    'to call a spade, a spade': '',
    'too many cooks spoil the broth': '',
    'two in distress makes sorrow less': '',
    'variety is the spice of life': '',
    'when in Rome, do as the Romans do': '',
    'when one is hungry, everything tastes good': '',
    "when there's a will, there's a way": '',
    "while the cat's away, the mice will play": '',
    "you can't have your cake and eat it too": '',
    "you can't make a silk purse out of a sow's ear": '',
    "you can't teach an old dog new tricks": '',
    'you have to take the rough with the smooth': '',
    "you scratch my back, i'll scratch yours": '',
}
