# ----------------------------------------------------------------
# Purpose:
# Defines the brand details that are rendered in all PDFs.
# ----------------------------------------------------------------
Type: 'Brand'
Title: 'VEL'
Authors:
  - '@person/MartinCastro.yaml'
