# ----------------------------------------------------------------
# Purpose:
# This file defines the sizes used in the renders.
# ----------------------------------------------------------------
Normal: 10
Subtitle: 20
Title: 40
