# ----------------------------------------------------------------
# Purpose:
# This file defines the sizes used in the renders.
# ----------------------------------------------------------------
Type: 'Dimensions'
Normal: 9
Subtitle: 12
Title: 36
Margin: 80
