# ----------------------------------------------------------------
# Purpose:
# This file defines the sizes used in the renders.
# ----------------------------------------------------------------
Type: 'Dimensions'
Small: 9
Normal: 12
Subtitle: 16
Title: 32
Break: 5
Margin: 80
