# ----------------------------------------------------------------
# Purpose:
# This file defines the sizes used in the renders.
# ----------------------------------------------------------------
Type: 'Dimensions'
Normal: 9
Subtitle: 16
Title: 32
Margin: 80
