# ----------------------------------------------------------------
# Purpose:
# This file defines the color pallete of the content rendered
#
# Reference:
# - https://flatuicolors.com/palette/defo
# ----------------------------------------------------------------
Type: 'Pallete'
Primary: '#706fd3'
Secondary: '#474787'
White: '#EDEDED'
Grey: '#e5e6ea'
Black: '#181818'
