# ----------------------------------------------------------------
# Purpose:
# This file defines the color pallete of the content rendered
#
# Reference:
# - https://flatuicolors.com/palette/defo
# ----------------------------------------------------------------
Type: 'Pallete'
Primary: '#337ab7'
Secondary: '#706fd3'
Tertiary: '#474787'
White: '#EDEDED'
# Grey: '#dcdde1'
Grey: '#e5e6ea'
Black: '#181818'
